name: unit-tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    # services:
    #   # Opcjonalnie: dodaj serwisy dla bazy danych testowej
    #   postgres:
    #     image: postgres:13
    #     env:
    #       POSTGRES_PASSWORD: postgres
    #       POSTGRES_DB: test_db
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        # Uruchom testy jednostkowe
        pytest tests/unit/ -v
        
  # lint:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #   - uses: actions/checkout@v3
    
  #   - name: Set up Python 3.11
  #     uses: actions/setup-python@v4
  #     with:
  #       python-version: 3.11
        
  #   - name: Install linting tools
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install flake8 black isort
        
  #   - name: Run linters
  #     run: |
  #       # Sprawdź formatowanie kodu
  #       black --check .
        
  #       # Sprawdź importy
  #       isort --check-only .
        
  #       # Sprawdź jakość kodu
  #       flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics